name: Cypress Tests

on:

 push:

   branches:

     - main

jobs:

 cypress-run:

   runs-on: ubuntu-latest

   strategy:

     fail-fast: false

   steps:

     - name: Checkout

       uses: actions/checkout@v4

     - name: Checkout

       uses: actions/checkout@v4

       with:

         path: server/api-bytebank

     - name: Start Server BackEnd

       run: |

         cd server/api-bytebank

         npm install

         npm run start-api &

         until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080)" == "200" ]; do

           echo "Waiting for server to start..."

           sleep 1

         done

         echo "Server is running successfully."

       working-directory: server/api-bytebank

     - name: Start Web App FrontEnd

       run: |

         npm install

         npm start &

     - name: Install Cypress Dependencies         
       run: |

        npm ci

     - name: Run Cypress Tests

       uses: cypress-io/github-action@v6

       with:

         spec: cypress/e2e/

         wait-on: 'http://localhost:3000,http://localhost:8080'

         record: true